version: 2.1

orbs:
  percy: percy/agent@0.1.2

default_steps: &default_steps
  steps:
    - checkout
    - run: npm ci
    - run: npm test

jobs:
  node_8:
    docker:
      - image: circleci/node:8-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_steps
  node_10_with_percy:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:10-browsers
    parallelism: 3
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - node_8
      - node_10_with_percy
      - percy/finalize_all:
          requires:
            - node_10_with_percy
